"""add reminders_enabled to users

Revision ID: 1c77ce916ff8
Revises: ccb08a3f2b25
Create Date: 2026-07-22 18:25:02.860428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c77ce916ff8'
down_revision: Union[str, Sequence[str], None] = 'ccb08a3f2b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reminders_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminders_enabled')
    # ### end Alembic commands ###
