"""add_institution_columns

Revision ID: 234990753f72
Revises: 1fbcb9eb5522
Create Date: 2026-07-20 18:04:00.137258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '234990753f72'
down_revision: Union[str, Sequence[str], None] = '1fbcb9eb5522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('institutions', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('institutions', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('institutions', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('institutions', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('institutions', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('institutions', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('institutions', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('institutions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('institutions', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('institutions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('institutions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('institutions_code_key'), 'institutions', type_='unique')
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=True)
    op.create_unique_constraint(None, 'institutions', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'institutions', type_='unique')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.create_unique_constraint(op.f('institutions_code_key'), 'institutions', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('institutions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('institutions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('institutions', 'code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('institutions', 'is_active')
    op.drop_column('institutions', 'logo_url')
    op.drop_column('institutions', 'postal_code')
    op.drop_column('institutions', 'country')
    op.drop_column('institutions', 'state')
    op.drop_column('institutions', 'city')
    op.drop_column('institutions', 'website')
    op.drop_column('institutions', 'phone')
    op.drop_column('institutions', 'email')
    # ### end Alembic commands ###
