"""add_embedding_metadata_to_kb_and_scraped_sources

Revision ID: a6ec2b8c4327
Revises: e0381b5a3843
Create Date: 2026-08-17 18:33:01.558731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ec2b8c4327'
down_revision: Union[str, Sequence[str], None] = 'e0381b5a3843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('scraped_sources', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('scraped_sources', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_sources', 'embedding_dimension')
    op.drop_column('scraped_sources', 'embedding_model')
    op.drop_column('knowledge_base', 'embedding_dimension')
    # ### end Alembic commands ###
